# Generated by Django 5.2.7 on 2025-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('person_name', models.CharField(max_length=100)),
                ('story_text', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='stories/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube Link')),
            ],
        ),
    ]
